#!/usr/bin/env python3
"""Generate ``src/llms_txt.py`` from the canonical metadata.

Usage::

    python scripts/generate_llms_txt.py            # writes to src/llms_txt.py
    python scripts/generate_llms_txt.py /tmp/out    # writes to /tmp/out/llms_txt.py

The generated file is a self-contained Python module with zero imports,
which is required by the Pyodide runtime used by Cloudflare Workers.

Source of truth: vectorize-mcp-tool/src/vectorize_mcp_tool/metadata.py
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

# Ensure the MCP tool package is importable
_repo_root = Path(__file__).resolve().parent.parent
_mcp_tool_src = _repo_root / "vectorize-mcp-tool" / "src"
if str(_mcp_tool_src) not in sys.path:
    sys.path.insert(0, str(_mcp_tool_src))

from vectorize_mcp_tool.metadata import render_llms_txt  # noqa: E402


def generate(output_dir: Path | None = None) -> Path:
    """Generate ``llms_txt.py`` and return the output path."""
    if output_dir is None:
        output_dir = _repo_root / "src"

    content = render_llms_txt()

    # Escape triple-quotes in the content (just in case)
    safe_content = content.replace('"""', r'\"\"\""')

    header = (
        '"""llms.txt content -- AUTO-GENERATED by scripts/generate_llms_txt.py\n'
        "\n"
        "Source of truth: vectorize-mcp-tool/src/vectorize_mcp_tool/metadata.py\n"
        "Do not edit this file directly.  Run:  python scripts/generate_llms_txt.py\n"
        '"""\n'
        "\n"
        "\n"
        "def get_llms_txt() -> str:\n"
        '    """Return the llms.txt content string."""\n'
        '    return """\\\n'
    )
    module_text = header + safe_content + '"""\n'

    out_path = output_dir / "llms_txt.py"
    out_path.write_text(module_text, encoding="utf-8")
    return out_path


def main() -> None:
    """CLI entry point."""
    output_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    out = generate(output_dir)
    print(f"Generated {out}")


if __name__ == "__main__":
    main()
