"""llms.txt content -- AUTO-GENERATED by scripts/generate_llms_txt.py

Source of truth: vectorize-mcp-tool/src/vectorize_mcp_tool/metadata.py
Do not edit this file directly.  Run:  python scripts/generate_llms_txt.py
"""


def get_llms_txt() -> str:
    """Return the llms.txt content string."""
    return """\
# Vectorize MCP Worker
> Production-Grade Hybrid RAG with Multimodal Support on Cloudflare Edge

## Overview
Interact with the Vectorize knowledge base deployed on Cloudflare Workers. Supports hybrid semantic + keyword search with Reciprocal Rank Fusion (RRF) and cross-encoder reranking, document ingestion with automatic recursive chunking (15 % overlap), image ingestion with AI-generated descriptions (Llama 4 Scout vision + OCR), visual similarity search, index statistics, document/image retrieval, listing, deletion, license management, and database reset (requires passphrase). Use the 'operation' parameter to select the action.

## Capabilities
- Hybrid search (Vector + BM25) with Reciprocal Rank Fusion
- Cross-encoder reranking (@cf/baai/bge-reranker-base)
- Multimodal image processing (Llama 4 Scout vision + OCR)
- Visual similarity search across ingested images
- Recursive document chunking with 15% overlap
- One-time license key system
- MCP tool integration for AI agents (via vectorize-mcp-tool)
- Interactive dashboard playground
- Sub-second latency at edge

## API Endpoints

### Public (no authentication)
- GET / - API documentation and endpoint list
- GET /health/check - Health check and binding status
- GET /dashboard - Interactive playground UI
- GET /llms.txt - AI search engine optimization info (this document)

### Authenticated (Bearer token required)
- POST /search/multimodal - Hybrid semantic search returning documents + images
- POST /search/documents - Hybrid semantic search returning documents only
- POST /search/similar-images - Visual similarity search across ingested images
- POST /ingest/document - Ingest a text document with automatic chunking
- POST /ingest/image - Ingest an image with AI description and OCR
- GET /stats/index - Index statistics (vector count, document count, dimensions)
- GET /get/document/:id - Retrieve full text document by ID
- GET /get/image/:id - Retrieve full image document by ID
- GET /list/documents - List documents with pagination
- POST /init/reset-passphrase - Set or rotate the reset passphrase
- POST /reset/all - Wipe all databases (requires passphrase)
- POST /reset/documents - Wipe documents + vectors (requires passphrase)
- POST /reset/licenses - Wipe licenses only (requires passphrase)
- POST /license/validate - Validate a license key
- POST /license/create - Create a new license key
- GET /license/list - List all licenses
- POST /license/revoke - Revoke (deactivate) a license key
- DELETE /delete/document/:id - Delete a document by ID
- DELETE /delete/license/:key - Delete a license by key

## MCP Operations

All MCP operations should be performed through the **vectorize-mcp-tool** Python package, which provides both a CLI and a FastMCP stdio server for AI agents (Cursor, Claude Desktop, etc.).

Available operations:

### search_multimodal
Hybrid search returning documents and images with snippets and metadata. Combines vector similarity + BM25 keyword matching using RRF, optionally reranked by a cross-encoder model.
- Required params: query
- Optional params: top_k, rerank, snippet_length

### search_documents
Hybrid search returning documents only (no images). Same search pipeline as search_multimodal but filters out image results.
- Required params: query
- Optional params: top_k, rerank, snippet_length

### ingest
Add a text document with automatic recursive chunking (15 % overlap). Each chunk is embedded and stored in the vector index + D1 keyword store.
- Required params: id, content
- Optional params: category, title

### ingest_image
Ingest an image with AI-generated description (Llama 4 Scout vision), OCR extraction, and embedding. Requires an image URL.
- Required params: id, image_url
- Optional params: category, title, image_type

### stats
Return knowledge-base statistics: vector count, document count, dimensions.
- Required params: none
- Optional params: none

### delete
Remove a document (text or image) by ID from both the vector index and the keyword store.
- Required params: id
- Optional params: none

### get_document
Retrieve the full text document by ID, including metadata. Returns an error if the ID refers to an image document.
- Required params: id
- Optional params: none

### get_image
Retrieve the full image document by ID, including AI description and metadata. Returns an error if the ID refers to a text document.
- Required params: id
- Optional params: none

### list_documents
List documents with pagination, returning ID, title, category, and creation timestamp for each document.
- Required params: none
- Optional params: limit, offset

### license_validate
Validate a license key and return its plan, limits, and status.
- Required params: license_key
- Optional params: none

### license_create
Create a new license key for the given email address with the specified plan and limits.
- Required params: email
- Optional params: plan, max_documents, max_queries_per_day

### license_list
List all licenses with their keys, emails, plans, and limits.
- Required params: none
- Optional params: none

### license_revoke
Revoke (deactivate) a license key. The key remains in the database but becomes invalid.
- Required params: license_key
- Optional params: none

### delete_license
Permanently delete a license row from the database.
- Required params: license_key
- Optional params: none

### reset_all
Wipe ALL databases (documents, vectors, and licenses). Requires the reset passphrase configured via POST /init/reset-passphrase.
- Required params: passphrase
- Optional params: none

### reset_documents
Wipe documents and vectors only (licenses are preserved). Requires the reset passphrase.
- Required params: passphrase
- Optional params: none

### reset_licenses
Wipe licenses only (documents are preserved). Requires the reset passphrase.
- Required params: passphrase
- Optional params: none

## Parameters Reference

- **operation** (string) | enum: search_multimodal, search_documents, ingest, ingest_image, stats, delete, get_document, get_image, list_documents, license_validate, license_create, license_list, license_revoke, delete_license, reset_all, reset_documents, reset_licenses: Operation to perform. One of: 'search_multimodal', 'search_documents', 'ingest', 'ingest_image', 'stats', 'delete', 'get_document', 'get_image', 'list_documents', 'license_validate', 'license_create', 'license_list', 'license_revoke', 'delete_license', 'reset_all', 'reset_documents', 'reset_licenses'.
- **query** (string): Search query text. Required for search_multimodal and search_documents.
- **top_k** (integer) | default: 5 | range: 1-20: Number of results to return (1-20, default 5). Used by search operations.
- **rerank** (boolean) | default: True: Whether to use cross-encoder reranking via @cf/baai/bge-reranker-base (default true). Improves result quality at slight latency cost. Used by search operations.
- **snippet_length** (integer) | default: 200 | range: 50-500: Maximum snippet length in characters (50-500, default 200). Controls how much of each matching document is returned in search results.
- **id** (string): Document or image ID. Required for ingest, ingest_image, delete, get_document, and get_image.
- **content** (string): Full text content of the document to ingest. Required for 'ingest'.
- **category** (string): Optional category tag for 'ingest' and 'ingest_image'. Used for filtering.
- **title** (string): Optional title for 'ingest' and 'ingest_image'. Stored as metadata.
- **image_url** (string): Publicly accessible image URL for 'ingest_image'. The image will be fetched, described by the vision model, OCR'd, and embedded.
- **image_type** (string) | default: auto | enum: screenshot, diagram, photo, document, chart, auto: Image type hint for 'ingest_image' that influences the vision model prompt. One of: 'screenshot', 'diagram', 'photo', 'document', 'chart', 'auto'. Default: 'auto'.
- **license_key** (string): License key string. Required for license_validate, license_revoke, delete_license.
- **email** (string): Email address for license_create. The license will be associated with this email.
- **plan** (string) | default: standard | enum: standard, pro, enterprise: Plan tier for license_create. One of: 'standard', 'pro', 'enterprise'. Default: 'standard'.
- **max_documents** (integer): Maximum number of documents allowed for the license. Used by license_create.
- **max_queries_per_day** (integer): Maximum number of queries per day allowed for the license. Used by license_create.
- **limit** (integer) | default: 50 | range: 1-200: Pagination limit (1-200, default 50). Used by list_documents.
- **offset** (integer) | default: 0: Pagination offset (default 0). Used by list_documents.
- **passphrase** (string): Reset passphrase. Required for reset_all, reset_documents, and reset_licenses. Must be configured first via POST /init/reset-passphrase.

## Technical Stack
- Runtime: Cloudflare Workers (Python / Pyodide)
- Vector DB: Cloudflare Vectorize (384 dimensions, cosine)
- SQL: Cloudflare D1
- Embedding: @cf/baai/bge-small-en-v1.5 (384 dimensions)
- Reranker: @cf/baai/bge-reranker-base
- Vision: @cf/meta/llama-4-scout-17b-16e-instruct (via multimodal worker)

## Usage Examples

### Search
```bash
curl -X POST /search/multimodal -H "Authorization: Bearer KEY" -H "Content-Type: application/json" -d '{"query": "your question", "topK": 5, "rerank": true}'
```

### Ingest
```bash
curl -X POST /ingest/document -H "Authorization: Bearer KEY" -H "Content-Type: application/json" -d '{"id": "doc-1", "content": "...", "category": "docs"}'
```

## MCP Integration

All MCP operations should be performed through the **vectorize-mcp-tool** Python package. Install with `pip install vectorize-mcp-tool` or `uv pip install vectorize-mcp-tool`.

Configure your AI agent (Cursor, Claude Desktop, etc.) with:
```json
{
  "mcpServers": {
    "vectorize": {
      "command": "vectorize-mcp-server",
      "env": {
        "VECTORIZE_URL": "https://your-worker.workers.dev",
        "VECTORIZE_API_KEY": "your-api-key"
      }
    }
  }
}
```

## Links
- GitHub: https://github.com/bruj0/vectorize-mcp-worker-python
- Dashboard: /dashboard
"""
